{
 "title": "Pino HTTP Logs Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "app",
    "label": "Aplication",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   { "name": "status", "label": "Status Code", "query": "200,201,401,404,500, " },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Среднее время ответа",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    avg_over_time(\r\n        {app=~\"$app\", namespace=~\"$namespace\"}\r\n        |= \"responseTime\"\r\n        | json\r\n        | unwrap responseTime\r\n        [${__range}]\r\n    )\r\n)"
    }
   ]
  },
  {
   "title": "Success Requests 2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        | res_statusCode < 400\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Bad Requests 4xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        | res_statusCode >= 400 and res_statusCode < 500\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Errored Requests 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        | res_statusCode >= 500\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\", namespace=~\"$namespace\"} |= `statusCode` | json [${__range}]))",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(\n    {app=~\"$app\", namespace=~\"$namespace\"} \n    |= \"statusCode\"\n    | json\n    | keep res_statusCode\n    [1m]\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=~\"$app\", namespace=~\"$namespace\", level=~\"$level\"}\n| json\n| res_statusCode=~\"$status\""
    }
   ]
  }
 ]
}